sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
- DJANGO="1.8"
- DJANGO="1.9"
- DJANGO="1.10"
- DJANGO="1.11"
install: pip install tox-travis codecov
script: tox
after_success: coverage combine && codecov
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=flake8
branches:
  only:
  - master
deploy:
  provider: pypi
  user: jwilhelm
  password:
    secure: R8/42JV5EkoHtVskFyZ5I+8ODZZL1ARYnlne43NbY57SgHmAB4wBeRy7kyu/20U74q0RQ6VaM6lYEZo983WKAyZZt4sUTgdylY0Y3stC3JRANJeLFTKkEKED6oeA2TtZMn697gOBEpCmsp2qOJdjtJxTDRuqP4X2thBlxAiHnK9xUhwguDR9EoHjB2PlCQ7sLLhxrSJclwkibj/IEEhT5N3ZcUTYjaCk0Q8SHVSBZrNgKieTJaOKHdz9RUzfEB/PZxYqUQkQJuE9v1YLEX5MPafQXnf6h4e2uKvJLj2R6H8Q2bJ2TfEuQhmU9kTfBhYZjewoC5+XIpjsda/6+yMBjZ1bUYlHGykwB24mKNSY9BjaC3GMZVOwYxUshEiuMFc7NHOPZXceQKG//IsyDk86E5eFv4CDf3cRlg1A4DyrHoDAT4R7pxb4XAG+nBK42cTZMbgFV1ggPFEzEJfsAKdTXD1h6Kp1zKaMs15r0M/QQAXk3isZKUzVnBxsdrUNscjwJzbhrk9ZOj05j+jX49ILzQrhzoDceSpf4mIjwdIzwf1yTkf8WmKh67/pcU7w+/ePto52K0mkdh6q/SlCienSoqyg2PWl48mGhtoztiZJw+tsW6Q0ojWmSH+R5MmireGASOZt//pnbwroPMApdAkxMM0/wWeTCBZTZzzc69u3fr0=
  on:
    tags: true
    branch: master
