sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
- DJANGO="1.8"
- DJANGO="1.9"
- DJANGO="1.10"
- DJANGO="1.11"
install: pip install tox-travis codecov
script: tox
after_success: coverage combine && codecov
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=flake8
branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: jwilhelm
  password:
    secure: "ja8rqjH06yjMy2P0Z11SsfE7i+DO6M6C+NPMs4tDLewVRmdLMiSozSwGNR1kF//4uXluClMjztpKLyIi03B23I+qSD3xXieWA/GeMQ616tXxE2en94whD+bM2JvqCObpacVbTooD5RLHfOuT5Bb+vwaNlJBtN49QpvVO7HHOGYVDYcIrbVramNCSSM95rrSdw2d0zq4VdKDWBwfY5jJF6r0Bk/MVB3AqJYcyAW1LL9m17gEuj7cSS320nfm5c5vqNlZ7qwKJcgffTaILhjxukEqjRfqVvQUdG/QnSDYJ+BLLB6Za679M0z8YzDB2/VtNp4na4owGy4atzFhFhBqfLczYx97XSYKaYA7sY+DmUbLVqcwC3H/q4KkZdl9cxkGMPBoPmT+U3crqnsKN0oMwJtfmzT7qlPDTv8jxrtS1IgIC0Wwsn4ZT1Y9sXYHJKtl2OcbXQn18lynQ2yrTCiYUrSZNppUnKnw0ug1hM+NhO3xAXHyl/g1gEw90bOlbd0ZZD/VACldmwXM5YOa3X+RVNdxvhRy0XaPRNh+F5/iDGhuyUmFjhyMD58K8DENsDyuOPhQBWkcACNwq+2Yi/bGP+EQV1ynI4vrqt3J9KfYN/Y61bAe2Z4qCHTQwV+iP5EYDXZDH4VeFEVGrxiX0t8V5LT7XgcOd18obrj+USi66a6s="
  on:
    tags: true
    python: 3.6
    condition: $TOXENV = flake8
    distributions: sdist bdist_wheel
    repo: tarkatronic/django-excel-response
