sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
- DJANGO="1.8"
- DJANGO="1.9"
- DJANGO="1.10"
- DJANGO="1.11"
install: pip install tox-travis codecov
script: tox
after_success: coverage combine && codecov
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=flake8
branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: jwilhelm
  password:
    secure: WmUOadBn+apJbmMsUQgGnF3SLjMjO540FGsyyPoSkcVEIPHQdPAYpAIVe8GpGdPz4Orp7tCqIddCoL4pbu3ne8oly32aDVmnn/FIVRc1qacDNN+bbwewEtl36g4uWDA395fTH2RHoI5aekQNp23/Lz/pP6zMW4mz6AFsN4p4JtGokrwqeJ4R1AyzyW4b8QPX7gT8KMf/cYkbxwhHIdMbG9nnldXJFFcrvB9MearUjquXf2Kag9vVJ8hZGYlFjx2woHPfLD8beMspSnnMlheWDaRrC68kQ4pHtuMCtku/h2reAx64VoMivjoptCb3nSNloLCQ87Ymoj+IvICWksUTcAZCttQX40Om5ugC3HTp/rAGXmjR1JxsWU+1DqIuQXPi5F9vTvCif/QCn4phVFGmjvs8wT+GuIJ+TSJPdPrFjF2YIWjJNZnkqSe1e4o4L/WkjLPsS5+FCCq4AprZ0yFgUUpy3iCp60Bg7/LIT+Co/yBWllZInWZyJ2Y4WcOypRyfXlnds8Tdwryylqp3kWixA/0HvPjXJb/R8m4SJGPztUpmH/4l4GJ9O72sXuQbp1lP09Attq1g5gKzblIel6je199ydHOE5hlnaexwC6ZHBFmMVT/Abxzh1I4p2+Ah1pdxqa0SpLqpLVsc2PRWbZ7J8FIhBn7d9+n0ZhXBOmlXe9Y=
  on:
    tags: true
    python: 3.6
    condition: $TOXENV = flake8
    distributions: sdist bdist_wheel
    repo: tarkatronic/django-excel-response
