sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
- DJANGO="1.8"
- DJANGO="1.9"
- DJANGO="1.10"
- DJANGO="1.11"
install: pip install tox-travis codecov
script: tox
after_success: coverage combine && codecov
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=flake8
branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: jwilhelm
  password:
    secure: yy8Vwpp2XoxOP9NjRgPQ9/WepXeDHAP92zM3dKrtto7mFgt4IR00DVdCDi+3GUIHq19GiPqiw7QiGHupu80nSpl8twV6udvBFladyD16fRZlvyJGPEQKXgGBKGT3yds4fQmcddJ+66eVNIPB1YhfARyTCMxTrMiEWtO24LNeqv+c/WT8uEuSUjJdkC/FA8+Qn3Cq4tJGEQg3XMDUApbqLsA2TlAyCUVTKWKvTPx18NiXN5rXdR93v4Zt2O48fzhdKtncdiAzFNxu+H2LGVTbpMOvkbGpMs8oE1+Brf6gttViVGzaHaY65CFOFwEjh3TFBszXW3tz5bvrE2QzG5TL+duAgNBwArelS/vmOwNReachP4/YGA+Dp6o+/UQgml7+LFo68rU8ylkhAsTRZF3k6XN+7g0Hx1bdVlTzoR6agCj4ID59ahDZtgOnzk1oVf9K1krovK7pXa17nnWOAkdkE2YpHIZUl3cVyC0XA86zuDyFSP5n3M63atOByax4V4jSkf5/qoTWuJkBPSSmcxJukAj0FnCWWx5fVI5B4u9jvnRLudYejBMJVB+Xy/tLw7FVn1CCOK7tdMyU/yW+DFbh/q7jt/EUeTskT1vyPYxAGtHZxkgk81oaV9/v0GJF6btPSJ5PQLOn9NqTBVmrm++BcwHF+5LF/SFnfcOK24fOhCw=
  on:
    tags: true
    python: 3.6
    condition: $TOXENV = flake8
    distributions: sdist bdist_wheel
    repo: tarkatronic/django-excel-response
